-- Create a exercises.sql file that contains a INSERT statement for inserting all of Lukes data into the database
INSERT INTO exercises
    (name, type_id, focus_id, warmup, cooldown, genre, instrument, teacher, description, directions, remember, minimum_time_minutes, bpm_min, bpm_max, video_link)
VALUES
('Down Strokes', 1, 1, TRUE, TRUE, 'Speed & Agility', 'Practice Pad', 'John Doe', 'Practice down strokes on the practice pad.', 
ARRAY['1 full stroke with right hand (RH), followed by 1 full stroke with left hand (LH). Repeat 16x, creating constant eighth notes.'],
ARRAY['Go slow!', 'Strive for an even sound between both hands.', 'If the stick falls out of your hand, that''s okay. It means you are not gripping the stick too hard.'],
5, 80, 100, 'https://example.com/video1'),
('Taps & Up Strokes', 1, 1, TRUE, TRUE, 'Speed & Agility', 'Practice Pad', 'Jane Smith', 'Work on taps and up strokes.', 
ARRAY['1. 4 full strokes (eighth notes) followed by 1 downstroke (quarter note) x8'],
ARRAY['Go slow!', 'Strive for an even sound between both hands.', 'If the stick falls out of your hand, that''s okay. It means you are not gripping the stick too hard.'],
10, 80, 120, 'https://example.com/video2'),
('Stone "killer" pt 1 - Hands', 2, 2, TRUE, TRUE, 'Precision & Timekeeping', 'Drum Set', 'Mike Johnson', 'Practice precision with hand strokes.',
ARRAY['1 full stroke with right hand (RH), followed by 1 full stroke with left hand (LH). Repeat 16x, creating constant eighth notes.'],
ARRAY['Go slow!', 'Strive for an even sound between both hands.', 'If the stick falls out of your hand, that''s okay. It means you are not gripping the stick too hard.'],
15, 50, 80, 'https://example.com/video3'),
('Stone "killer" pt 2 - Hands', 2, 2, TRUE, TRUE, 'Precision & Timekeeping', 'Drum Set', 'Mike Johnson', 'Continuation of part 1 with hand strokes.',
ARRAY['1 full stroke with right hand (RH), followed by 1 full stroke with left hand (LH). Repeat 16x, creating constant eighth notes.'],
ARRAY['Go slow!', 'Strive for an even sound between both hands.', 'If the stick falls out of your hand, that''s okay. It means you are not gripping the stick too hard.'],
15, 50, 80, 'https://example.com/video4'),
('Foot Triplets', 3, 3, TRUE, TRUE, 'Style & Vocabulary', 'Snare Drum', 'Sarah Davis', 'Work on foot triplets with a snare drum.',
ARRAY['1. 4 full strokes (eighth notes) followed by 1 downstroke (quarter note) x8'],
ARRAY['Go slow!', 'Strive for an even sound between both hands.', 'If the stick falls out of your hand, that''s okay. It means you are not gripping the stick too hard.'],
20, 60, 100, 'https://example.com/video5'),
('Stone "killer" pt 1 - Feet', 2, 2, TRUE, TRUE, 'Precision & Timekeeping', 'Drum Set', 'Mike Johnson', 'Practice precision with foot strokes.',
ARRAY['1 full stroke with right hand (RH), followed by 1 full stroke with left hand (LH). Repeat 16x, creating constant eighth notes.'],
ARRAY['Go slow!', 'Strive for an even sound between both hands.', 'If the stick falls out of your hand, that''s okay. It means you are not gripping the stick too hard.'],
15, 60, 120, 'https://example.com/video6'),
('Stone "killer" pt 2 - Feet', 2, 2, TRUE, TRUE, 'Precision & Timekeeping', 'Drum Set', 'Mike Johnson', 'Continuation of part 1 with foot strokes.',
ARRAY['1 full stroke with right hand (RH), followed by 1 full stroke with left hand (LH). Repeat 16x, creating constant eighth notes.'],
ARRAY['Go slow!', 'Strive for an even sound between both hands.', 'If the stick falls out of your hand, that''s okay. It means you are not gripping the stick too hard.'],
15, 60, 120, 'https://example.com/video7'),
('Double Stroke Roll', 1, 1, TRUE, TRUE, 'Speed & Agility', 'Practice Pad', 'John Doe', 'Master the double stroke roll on the practice pad.',
ARRAY['1 full stroke with right hand (RH), followed by 1 full stroke with left hand (LH). Repeat 16x, creating constant eighth notes.'],
ARRAY['Go slow!', 'Strive for an even sound between both hands.', 'If the stick falls out of your hand, that''s okay. It means you are not gripping the stick too hard.'],
10, 70, 160, 'https://example.com/video8'),
('Single Stroke Roll', 1, 1, TRUE, TRUE, 'Speed & Agility', 'Practice Pad', 'John Doe', 'Practice the single stroke roll on the practice pad.',
ARRAY['1 full stroke with right hand (RH), followed by 1 full stroke with left hand (LH). Repeat 16x, creating constant eighth notes.'],
ARRAY['Go slow!', 'Strive for an even sound between both hands.', 'If the stick falls out of your hand, that''s okay. It means you are not gripping the stick too hard.'],
10, 60, 120, 'https://example.com/video9'),
('Flam Paradiddle', 3, 3, TRUE, TRUE, 'Style & Vocabulary', 'Snare Drum', 'Sarah Davis', 'Master the flam paradiddle on the snare drum.',
ARRAY['Alternate between right and left hand flam paradiddles for 2 minutes.'],
ARRAY['Stay relaxed!', 'Focus on wrist control.', 'Maintain consistent spacing between flams.'],
10, 70, 120, 'https://example.com/video10'),
('Ratamacue', 3, 3, TRUE, TRUE, 'Style & Vocabulary', 'Snare Drum', 'John Smith', 'Work on ratamacue rudiments on the snare drum.',
ARRAY['Play ratamacues at various tempos for 5 minutes.'],
ARRAY['Pay attention to stick heights.', 'Gradually increase speed for a challenge.', 'Practice with a metronome.'],
15, 60, 100, 'https://example.com/video11'),
('Buzz Rolls', 1, 2, TRUE, TRUE, 'Precision & Timekeeping', 'Snare Drum', 'Jane Johnson', 'Develop precision with buzz rolls on the snare drum.',
ARRAY['Perform buzz rolls with both hands for 3 minutes.'],
ARRAY['Focus on maintaining even pressure.', 'Practice controlling the buzz sound.', 'Use ear protection for extended practice.'],
20, 40, 90, 'https://example.com/video12'),
('Eighth Note to Triplets', 4, 4, TRUE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'David Wilson', 'Transition from eighth notes to triplets in drumming patterns.',
ARRAY['Create grooves transitioning from eighth notes to triplets.'],
ARRAY['Experiment with different accent patterns.', 'Record yourself for self-evaluation.', 'Collaborate with a bassist for rhythm practice.'],
15, 60, 120, 'https://example.com/video13'),
('7/8 Grooving', 4, 4, TRUE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'Sarah Davis', 'Groove in the challenging time signature of 7/8.',
ARRAY['Develop grooves in 7/8 time signature.'],
ARRAY['Count aloud while playing.', 'Practice fills in odd time signatures.', 'Listen to 7/8 music for inspiration.'],
20, 80, 120, 'https://example.com/video14'),
('Storytelling Arc', 4, 4, TRUE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'John Smith', 'Create drumming patterns with a storytelling arc.',
ARRAY['Compose drum patterns that tell a story through dynamics.'],
ARRAY['Experiment with tempo fluctuations.', 'Improvise with emotion in mind.', 'Connect with the music on a personal level.'],
10, 80, 160, 'https://example.com/video15'),
('Linear Kick Fills', 1, 1, TRUE, TRUE, 'Speed & Agility', 'Drum Set', 'Mike Johnson', 'Master linear kick drum fills on the drum set.',
ARRAY['Practice linear kick fills at various tempos.'],
ARRAY['Use a metronome to develop timing.', 'Combine linear patterns into longer phrases.', 'Work on smooth transitions between kicks and snares.'],
15, 50, 80, 'https://example.com/video16'),
('Bossa Nova Variations', 4, 4, TRUE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'David Wilson', 'Explore different Bossa Nova rhythm variations.',
ARRAY['Experiment with Bossa Nova patterns and variations.'],
ARRAY['Incorporate ghost notes for dynamics.', 'Listen to Bossa Nova music for inspiration.', 'Collaborate with other musicians for a full ensemble experience.'],
10, 60, 100, 'https://example.com/video17'),
('Hum While Exploring', 4, 4, TRUE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'Jane Johnson', 'Engage in creative drumming while humming melodies.',
ARRAY['Play the drum set while humming melodies or rhythms.'],
ARRAY['Improvise freely while humming.', 'Experiment with vocal percussion.', 'Record your sessions for creative exploration.'],
15, 70, 160, 'https://example.com/video18'),
('Changing Dynamics', 4, 4, TRUE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'Sarah Davis', 'Practice changing dynamics within drum patterns.',
ARRAY['Create drum grooves with dynamic shifts.'],
ARRAY['Use dynamics to express emotion.', 'Experiment with sudden and gradual dynamic changes.', 'Collaborate with a guitarist for dynamic contrast.'],
20, 40, 90, 'https://example.com/video19'),
('Quintuplet Accents', 4, 4, TRUE, FALSE, 'Creativity & Improvisation', 'Drum Set', 'David Wilson', 'Work on accents with quintuplet patterns.',
ARRAY['Create drum patterns emphasizing quintuplet accents.'],
ARRAY['Experiment with accent placements.', 'Use dynamics to make accents stand out.', 'Collaborate with a bassist for rhythmic contrast.'],
15, 70, 120, 'https://example.com/video20'),
('Nonuplet Accents', 4, 4, FALSE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'Jane Johnson', 'Explore accents in nonuplet drumming patterns.',
ARRAY['Develop nonuplet drum patterns with varying accents.'],
ARRAY['Practice controlling the speed of nonuplets.', 'Record your performance for accuracy evaluation.', 'Experiment with ghost notes for added complexity.'],
20, 60, 100, 'https://example.com/video21'),
('9/8 Grooving', 4, 4, TRUE, FALSE, 'Creativity & Improvisation', 'Drum Set', 'Mike Johnson', 'Groove in the challenging time signature of 9/8.',
ARRAY['Create grooves in 9/8 time signature.'],
ARRAY['Use a metronome to maintain the 9/8 feel.', 'Explore polyrhythmic possibilities.', 'Collaborate with a pianist for harmonic richness.'],
15, 80, 120, 'https://example.com/video22'),
('11/8 Grooving', 4, 4, FALSE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'Sarah Davis', 'Challenge yourself with grooves in 11/8 time.',
ARRAY['Develop grooves in 11/8 time signature.'],
ARRAY['Focus on counting 11/8 accurately.', 'Experiment with metric modulation.', 'Collaborate with a saxophonist for melodic exploration.'],
20, 40, 90, 'https://example.com/video23'),
('Displaced 16th Note - Hands', 2, 2, TRUE, FALSE, 'Precision & Timekeeping', 'Drum Set', 'John Smith', 'Master displaced 16th notes with hand strokes.',
ARRAY['Practice displaced 16th note patterns with both hands.'],
ARRAY['Use a metronome to maintain timing.', 'Work on smooth transitions between displaced notes.', 'Record your practice to track progress.'],
10, 60, 120, 'https://example.com/video24'),
('Displaced 16th Note - Groove', 2, 2, FALSE, TRUE, 'Precision & Timekeeping', 'Drum Set', 'Mike Johnson', 'Incorporate displaced 16th notes into grooves.',
ARRAY['Create drum grooves featuring displaced 16th notes.'],
ARRAY['Focus on groove pocket and timing.', 'Experiment with different displaced patterns.', 'Collaborate with a guitarist for rhythmic synergy.'],
15, 60, 100, 'https://example.com/video25'),
('Slow Burn', 4, 4, TRUE, FALSE, 'Creativity & Improvisation', 'Drum Set', 'David Wilson', 'Practice slow and controlled drumming with dynamics.',
ARRAY['Create slow and expressive drumming patterns.'],
ARRAY['Emphasize dynamics to build tension.', 'Explore various crescendos and decrescendos.', 'Collaborate with a vocalist for a dramatic effect.'],
20, 70, 160, 'https://example.com/video26'),
('16th to Quintuplet Groove', 4, 4, FALSE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'Jane Johnson', 'Transition between 16th notes and quintuplets in grooves.',
ARRAY['Develop drum grooves that shift between 16th notes and quintuplets.'],
ARRAY['Practice smooth transitions between rhythms.', 'Experiment with changing accents.', 'Collaborate with a bassist for rhythmic exploration.'],
10, 80, 120, 'https://example.com/video27'),
('Elvin Jones - Lonnie's Lament', 4, 4, FALSE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'Sarah Davis', 'Explore Elvin Jones' drumming in "Lonnie's Lament."',
ARRAY['Study and play along with Elvin Jones' performance in "Lonnie's Lament."'],
ARRAY['Capture the essence of Elvin Jones' style.', 'Experiment with polyrhythms and improvisation.', 'Collaborate with a pianist for a jazz experience.'],
20, 40, 90, 'https://example.com/video29'),
('Tony Williams - Hat and Beard', 4, 4, TRUE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'John Smith', 'Explore Tony Williams' drumming in "Hat and Beard."',
ARRAY['Study and play along with Tony Williams' performance in "Hat and Beard."'],
ARRAY['Capture the spirit of Tony Williams' style.', 'Experiment with improvisation and ghost notes.', 'Collaborate with a bassist for a jazz fusion experience.'],
15, 70, 120, 'https://example.com/video30'),
('Tony Allen - Water No Get Enemy', 4, 4, TRUE, FALSE, 'Creativity & Improvisation', 'Drum Set', 'Mike Johnson', 'Groove to Tony Allen's "Water No Get Enemy."',
ARRAY['Study and jam to Tony Allen's legendary rhythm in "Water No Get Enemy."'],
ARRAY['Focus on the groove and pocket of the beat.', 'Experiment with syncopated accents.', 'Collaborate with a guitarist for Afrobeat vibes.'],
20, 60, 100, 'https://example.com/video31'),
('Comping Over the Bar Line', 4, 4, FALSE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'Jane Johnson', 'Practice comping over the bar lines in jazz drumming.',
ARRAY['Develop the skill of comping across bar lines in jazz standards.'],
ARRAY['Pay attention to phrasing and anticipation.', 'Experiment with different jazz standards.', 'Collaborate with a pianist for harmonic exploration.'],
15, 80, 120, 'https://example.com/video32'),
('Linear Kick Fills', 1, 1, FALSE, FALSE, 'Speed & Agility', 'Drum Set', 'David Wilson', 'Master linear kick drum fills on the drum set.',
ARRAY['Practice linear kick fills at various tempos.'],
ARRAY['Use a metronome to develop timing.', 'Combine linear patterns into longer phrases.', 'Work on smooth transitions between kicks and snares.'],
15, 50, 80, 'https://example.com/video33'),
('Swung to Straight', 4, 4, TRUE, FALSE, 'Creativity & Improvisation', 'Drum Set', 'Sarah Davis', 'Explore transitioning between swung and straight grooves.',
ARRAY['Create grooves that transition between swung and straight feels.'],
ARRAY['Focus on maintaining groove consistency.', 'Experiment with tempo changes.', 'Collaborate with a guitarist for rhythmic versatility.'],
20, 60, 120, 'https://example.com/video34'),
('Expand on Single Idea', 4, 4, FALSE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'John Smith', 'Expand upon a single rhythmic idea in your drumming.',
ARRAY['Take a simple rhythmic idea and develop it into a full composition.'],
ARRAY['Explore variations and orchestrations of the idea.', 'Record your progress to track development.', 'Collaborate with a vocalist for a unique performance.'],
10, 40, 90, 'https://example.com/video35'),
('Use of Silence', 4, 4, TRUE, FALSE, 'Creativity & Improvisation', 'Drum Set', 'Mike Johnson', 'Incorporate the use of silence in your drumming.',
ARRAY['Create grooves and patterns that utilize strategic pauses.'],
ARRAY['Focus on the impact of silence on groove.', 'Experiment with different durations of silence.', 'Collaborate with a saxophonist for dynamic interplay.'],
15, 60, 120, 'https://example.com/video36'),
('Cymbal Deep Listening', 4, 4, FALSE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'Jane Johnson', 'Deepen your listening skills with cymbal work.',
ARRAY['Focus on the nuances of cymbal sounds and textures.'],
ARRAY['Listen attentively to cymbal subtleties.', 'Experiment with cymbal accents and swells.', 'Collaborate with a cellist for sonic exploration.'],
20, 70, 160, 'https://example.com/video37'),
('Hum While Exploring', 4, 4, TRUE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'David Wilson', 'Engage in creative drumming while humming melodies.',
ARRAY['Play the drum set while humming melodies or rhythms.'],
ARRAY['Improvise freely while humming.', 'Experiment with vocal percussion.', 'Record your sessions for creative exploration.'],
15, 80, 100, 'https://example.com/video38'),
('Tony Allen - Water No Get Enemy', 4, 4, TRUE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'Jane Johnson', 'Explore Tony Allen's drumming in "Water No Get Enemy."',
ARRAY['Study and play along with Tony Allen's performance in "Water No Get Enemy."'],
ARRAY['Emulate Tony Allen's groove and feel.', 'Experiment with polyrhythms and syncopation.', 'Collaborate with a guitarist for an Afrobeat vibe.'],
15, 70, 120, 'https://example.com/video30'),
('Comping Over the Bar Line', 4, 4, TRUE, FALSE, 'Creativity & Improvisation', 'Drum Set', 'Mike Johnson', 'Practice comping over the bar line in jazz drumming.',
ARRAY['Develop comping patterns that cross bar lines.'],
ARRAY['Use a metronome to maintain timing.', 'Experiment with displaced accents.', 'Collaborate with a horn player for dynamic exchanges.'],
20, 60, 100, 'https://example.com/video31'),
('Linear Kick Fills', 1, 1, TRUE, FALSE, 'Speed & Agility', 'Drum Set', 'David Wilson', 'Master linear kick drum fills on the drum set.',
ARRAY['Practice linear kick fills at various tempos.'],
ARRAY['Use a metronome to develop timing.', 'Combine linear patterns into longer phrases.', 'Work on smooth transitions between kicks and snares.'],
15, 50, 80, 'https://example.com/video32'),
('Swung to Straight', 4, 4, FALSE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'Sarah Davis', 'Explore the transition from swung to straight rhythms.',
ARRAY['Create grooves that transition between swung and straight feels.'],
ARRAY['Pay attention to timing shifts.', 'Experiment with different swing ratios.', 'Collaborate with a bassist for rhythmic contrast.'],
10, 80, 160, 'https://example.com/video33'),
('LH Comping - Jazz', 4, 4, TRUE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'John Smith', 'Practice left-hand comping in jazz drumming.',
ARRAY['Develop comping patterns with your left hand in jazz drumming.'],
ARRAY['Focus on independence between hands.', 'Work on subtle accents and ghost notes.', 'Collaborate with a pianist for a classic jazz sound.'],
10, 60, 120, 'https://example.com/video34'),
('LH & RF Comping - Jazz', 4, 4, FALSE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'Jane Johnson', 'Explore left-hand and right-foot comping in jazz drumming.',
ARRAY['Develop comping patterns with your left hand and right foot in jazz drumming.'],
ARRAY['Coordinate between your limbs effectively.', 'Experiment with syncopated patterns.', 'Collaborate with a saxophonist for a full jazz ensemble experience.'],
15, 60, 100, 'https://example.com/video35'),
('Storytelling Arc', 4, 4, FALSE, FALSE, 'Creativity & Improvisation', 'Drum Set', 'Mike Johnson', 'Create drumming patterns with a storytelling arc.',
ARRAY['Compose drum patterns that tell a story through dynamics.'],
ARRAY['Experiment with tempo fluctuations.', 'Improvise with emotion in mind.', 'Connect with the music on a personal level.'],
10, 80, 160, 'https://example.com/video36'),
('Expand on Single Idea', 4, 4, FALSE, TRUE, 'Creativity & Improvisation', 'Drum Set', 'David Wilson', 'Expand upon a single drumming idea creatively.',
ARRAY['Take a simple drumming idea and develop it into a full groove.'],
ARRAY['Experiment with variations and embellishments.', 'Record your progress for creative exploration.', 'Collaborate with a guitarist for added layers.'],
15, 40, 90, 'https://example.com/video37'),
('Use of Silence', 4, 4, FALSE, FALSE, 'Creativity & Improvisation', 'Drum Set', 'Sarah Davis', 'Explore the power of silence in drumming.',
ARRAY['Create drum patterns that incorporate deliberate pauses.'],
ARRAY['Practice controlling silence to build tension.', 'Experiment with unexpected moments of stillness.', 'Collaborate with a vocalist for dramatic effects.'],
20, 70, 160, 'https://example.com/video38'),
('Cymbal Deep Listening', 4, 4, TRUE, FALSE, 'Creativity & Improvisation', 'Drum Set', 'John Smith', 'Improve your cymbal playing through deep listening.',
ARRAY['Listen to cymbal sounds and their nuances.'],
ARRAY['Focus on cymbal articulation and tone.', 'Experiment with various cymbal techniques.', 'Record cymbal sounds for analysis.'],
10, 60, 100, 'https://example.com/video39');