INSERT INTO
    exercises (
        name,
        type_id,
        focus_id,
        warmup,
        cooldown,
        genre,
        instrument,
        teacher,
        description,
        directions,
        remember,
        minimum_time_minutes,
        bpm_min,
        bpm_max,
        video_link
    )
VALUES
    (
        'Advanced Flamenco Guitar',
        4,
        4,
        TRUE,
        TRUE,
        'Flamenco',
        'Guitar',
        'Carlos Hernandez',
        'Advance your Flamenco guitar skills with intricate techniques.',
        '{"Master Flamenco rasgueado strumming.", "Practice picado and alzapua techniques.", "Explore various Flamenco palos (styles)." }',
        '{"Maintain a steady rhythm throughout.", "Experiment with rasgueado variations.", "Collaborate with a percussionist for rhythm exploration."}',
        15,
        80,
        140,
        'https://www.example.com/video45'
    ),
    (
        'Latin Percussion Soloing',
        4,
        4,
        TRUE,
        TRUE,
        'Latin',
        'Percussion',
        'Ana Ramirez',
        'Develop your Latin percussion soloing abilities.',
        '{"Learn clave patterns and their variations.", "Practice improvisation within Latin rhythms.", "Focus on dynamics and accents."}',
        '{"Use multiple percussion instruments for timbral variety.", "Experiment with call and response phrasing.", "Record your solos for self-improvement."}',
        20,
        70,
        130,
        'https://www.example.com/video46'
    ),
    (
        'Slap Bass Grooves',
        4,
        4,
        TRUE,
        FALSE,
        'Funk',
        'Bass Guitar',
        'Marcus Johnson',
        'Get funky with slap bass grooves and techniques.',
        '{"Master slap and pop techniques.", "Practice syncopated basslines.", "Explore slap harmonics and ghost notes."}',
        '{"Maintain a tight groove with the drummer.", "Experiment with left-hand muting.", "Collaborate with a funk band for a tight rhythm section."}',
        15,
        60,
        110,
        'https://www.example.com/video47'
    ),
    (
        'Advanced Jazz Drumming',
        4,
        4,
        TRUE,
        TRUE,
        'Jazz',
        'Drum Set',
        'Emily Davis',
        'Enhance your jazz drumming with advanced concepts.',
        '{"Explore polyrhythmic grooves.", "Practice comping over complex chord changes.", "Focus on brush and mallet techniques."}',
        '{"Maintain a steady pulse in odd time signatures.", "Experiment with extended drum solos.", "Collaborate with a jazz ensemble for ensemble experience."}',
        20,
        60,
        120,
        'https://www.example.com/video48'
    ),
    (
        'Flute Embouchure Mastery',
        4,
        4,
        TRUE,
        TRUE,
        'Classical',
        'Flute',
        'Isabella Martinez',
        'Master the art of flute embouchure for classical performance.',
        '{"Develop control over tone and dynamics.", "Practice articulation techniques.", "Explore expressive vibrato and trills."}',
        '{"Maintain consistent breath support.", "Experiment with legato and staccato phrasing.", "Collaborate with a pianist for chamber music."}',
        15,
        60,
        100,
        'https://www.example.com/video49'
    ),
    (
        'Fretless Bass Techniques',
        4,
        4,
        TRUE,
        FALSE,
        'Jazz',
        'Bass Guitar',
        'Robert Turner',
        'Explore the world of fretless bass with advanced techniques.',
        '{"Master fretless intonation.", "Practice slides and glissandos.", "Focus on fretless soloing and improvisation."}',
        '{"Use your ears to develop intonation.", "Experiment with microtonal bends.", "Collaborate with a jazz quartet for fretless exploration."}',
        20,
        60,
        110,
        'https://www.example.com/video50'
    ),
    (
        'Advanced Classical Piano',
        4,
        4,
        TRUE,
        TRUE,
        'Classical',
        'Piano',
        'Sophia Anderson',
        'Advance your classical piano skills with complex compositions.',
        '{"Study advanced classical repertoire.", "Practice intricate fingerings and phrasing.", "Focus on expressive interpretation."}',
        '{"Maintain even tempo in challenging passages.", "Experiment with different pedaling techniques.", "Collaborate with a cellist for chamber music."}',
        15,
        60,
        120,
        'https://www.example.com/video51'
    ),
    (
        'Advanced Blues Harmonica',
        4,
        4,
        TRUE,
        FALSE,
        'Blues',
        'Harmonica',
        'Benjamin Miller',
        'Develop your blues harmonica skills with advanced techniques.',
        '{"Master bending and overblowing.", "Practice blues scale improvisation.", "Focus on expressive tone and phrasing."}',
        '{"Use vibrato for added expressiveness.", "Experiment with tongue-blocking.", "Collaborate with a blues band for harmonica solos."}',
        20,
        70,
        130,
        'https://www.example.com/video52'
    ),
    (
        'Advanced Jazz Guitar Chords',
        4,
        4,
        TRUE,
        TRUE,
        'Jazz',
        'Guitar',
        'Olivia Parker',
        'Enhance your jazz guitar playing with advanced chord voicings.',
        '{"Learn extended and altered chord shapes.", "Practice chord melody arrangements.", "Focus on chord substitutions and progressions."}',
        '{"Maintain smooth voice leading in chord progressions.", "Experiment with inversions and quartal harmony.", "Collaborate with a jazz vocalist for harmony exploration."}',
        15,
        80,
        140,
        'https://www.example.com/video53'
    ),
    (
        'Tabla Rhythmic Patterns',
        4,
        4,
        TRUE,
        TRUE,
        'World',
        'Percussion',
        'Ravi Patel',
        'Explore intricate rhythmic patterns on the tabla.',
        '{"Learn traditional and contemporary tabla compositions.", "Practice complex tala rhythms.", "Focus on finger technique and hand coordination."}',
        '{"Maintain precise timekeeping in complex rhythms.", "Experiment with solo tabla performances.", "Collaborate with a sitar player for traditional Indian music."}',
        20,
        70,
        130,
        'https://www.example.com/video54'
    ),
    (
        'Advanced Jazz Saxophone',
        4,
        4,
        TRUE,
        TRUE,
        'Jazz',
        'Saxophone',
        'Michael Johnson',
        'Advance your jazz saxophone skills with complex improvisations.',
        '{"1. Explore advanced jazz scales and modes.", "2. Practice intricate saxophone phrasing.", "3. Focus on dynamic expression."}',
        '{"1. Maintain consistent intonation and tone quality.", "2. Experiment with alternate fingerings.", "3. Collaborate with a jazz trio for ensemble experience."}',
        20,
        80,
        140,
        'https://www.example.com/video55'
    ),
    (
        'Advanced Flamenco Dance',
        4,
        4,
        TRUE,
        TRUE,
        'Flamenco',
        'Dance',
        'Isabella Rodriguez',
        'Develop your Flamenco dance techniques with intricate footwork.',
        '{"1. Learn complex Flamenco footwork patterns.", "2. Practice precise heel and toe strikes.", "3. Explore various Flamenco styles."}',
        '{"1. Maintain a strong Flamenco posture.", "2. Experiment with intricate arm movements.", "3. Collaborate with a guitarist for live performances."}',
        15,
        70,
        120,
        'https://www.example.com/video56'
    ),
    (
        'Latin Jazz Piano Improvisation',
        4,
        4,
        TRUE,
        TRUE,
        'Latin',
        'Piano',
        'Carlos Martinez',
        'Enhance your Latin jazz piano skills with improvisational techniques.',
        '{"1. Explore Latin jazz chord progressions.", "2. Practice improvisation over Latin rhythms.", "3. Focus on creating melodic phrases."}',
        '{"1. Maintain a steady Latin groove.", "2. Experiment with chord extensions and voicings.", "3. Collaborate with a percussionist for Latin jazz fusion."}',
        20,
        70,
        130,
        'https://www.example.com/video57'
    ),
    (
        'Advanced Ballet Techniques',
        4,
        4,
        TRUE,
        TRUE,
        'Ballet',
        'Dance',
        'Sophia Anderson',
        'Advance your ballet skills with challenging techniques and choreography.',
        '{"1. Learn intricate ballet combinations and variations.", "2. Practice balance and turns.", "3. Focus on conveying emotion through dance."}',
        '{"1. Maintain proper ballet posture and alignment.", "2. Experiment with graceful arm movements.", "3. Collaborate with a live orchestra for classical ballet performances."}',
        15,
        60,
        110,
        'https://www.example.com/video58'
    ),
    (
        'Advanced Acoustic Guitar Fingerpicking',
        4,
        4,
        TRUE,
        FALSE,
        'Acoustic',
        'Guitar',
        'Olivia Parker',
        'Expand your acoustic guitar fingerpicking skills with complex patterns.',
        '{"1. Learn fingerstyle arrangements of classic songs.", "2. Practice fingerpicking with multiple fingers.", "3. Explore thumb and finger independence."}',
        '{"1. Maintain a steady rhythm in fingerstyle playing.", "2. Experiment with dynamic variations.", "3. Collaborate with a vocalist for acoustic duets."}',
        20,
        60,
        110,
        'https://www.example.com/video59'
    ),
    (
        'Full Strokes',
        1,
        1,
        TRUE,
        TRUE,
        'Drumming Technique',
        'Practice Pad',
        'John Smith',
        'Work on perfecting your full strokes on the practice pad.',
        '{"1. Focus on even stick height with each stroke.", "2. Practice both right and left hand full strokes.", "3. Maintain a steady tempo."}',
        '{"1. Use a mirror to check your technique.", "2. Experiment with different tempos.", "3. Keep your grip relaxed for better control."}',
        10,
        60,
        120,
        'https://www.example.com/video60'
    ),
    (
        'Down Strokes',
        1,
        1,
        TRUE,
        FALSE,
        'Drumming Technique',
        'Practice Pad',
        'Emily Davis',
        'Practice precise down strokes to build hand control.',
        '{"1. Use a metronome for timing.", "2. Focus on consistent downstroke technique.", "3. Gradually increase the tempo."}',
        '{"1. Pay attention to wrist motion.", "2. Experiment with different dynamics.", "3. Keep your strokes clean and controlled."}',
        10,
        60,
        100,
        'https://www.example.com/video61'
    ),
    (
        'Taps & Up Strokes',
        1,
        1,
        TRUE,
        FALSE,
        'Drumming Technique',
        'Practice Pad',
        'Laura Johnson',
        'Work on taps and upstrokes for versatile drumming technique.',
        '{"1. Practice tap strokes with control.", "2. Experiment with upstrokes for accents.", "3. Combine taps and upstrokes in patterns."}',
        '{"1. Use a metronome to maintain timing.", "2. Focus on wrist and finger control.", "3. Develop speed gradually."}',
        10,
        70,
        120,
        'https://www.example.com/video62'
    ),
    (
        'Stone "killer" pt 1 - Hands',
        1,
        1,
        TRUE,
        TRUE,
        'Drumming Technique',
        'Practice Pad',
        'Carlos Hernandez',
        'Begin the Stone "killer" exercise series with a focus on hand technique.',
        '{"1. Practice single strokes with each hand.", "2. Gradually increase speed.", "3. Work on control and consistency."}',
        '{"1. Use a metronome to track your progress.", "2. Record your sessions for analysis.", "3. Maintain a relaxed grip."}',
        15,
        80,
        140,
        'https://www.example.com/video63'
    ),
    (
        'Stone "killer" pt 2 - Hands',
        1,
        1,
        TRUE,
        TRUE,
        'Drumming Technique',
        'Practice Pad',
        'Isabella Martinez',
        'Continue the Stone "killer" exercise series with a focus on hand control and endurance.',
        '{"1. Practice double strokes with each hand.", "2. Gradually increase tempo.", "3. Maintain consistent hand heights."}',
        '{"1. Use a metronome for accurate timing.", "2. Focus on relaxed wrists and fingers.", "3. Challenge yourself with longer practice sessions."}',
        20,
        80,
        140,
        'https://www.example.com/video64'
    ),
    (
        'Foot Triplets',
        1,
        1,
        TRUE,
        FALSE,
        'Drumming Technique',
        'Drum Set',
        'Michael Johnson',
        'Improve your foot control with triplet patterns on the bass drum.',
        '{"1. Practice triplet patterns with the bass drum.", "2. Coordinate with hand patterns.", "3. Work on even spacing between notes."}',
        '{"1. Use a metronome to develop timing.", "2. Experiment with different triplet subdivisions.", "3. Maintain a relaxed foot technique."}',
        15,
        70,
        120,
        'https://www.example.com/video65'
    ),
    (
        'Stone "killer" pt 1 - Feet',
        1,
        1,
        TRUE,
        TRUE,
        'Drumming Technique',
        'Drum Set',
        'Natalie Carter',
        'Start the Stone "killer" series for foot technique development.',
        '{"1. Practice single strokes with each foot.", "2. Gradually increase speed.", "3. Focus on control and consistency."}',
        '{"1. Use a metronome to track your progress.", "2. Record your sessions for analysis.", "3. Maintain a relaxed foot technique."}',
        15,
        70,
        120,
        'https://www.example.com/video66'
    ),
    (
        'Stone "killer" pt 2 - Feet',
        1,
        1,
        TRUE,
        TRUE,
        'Drumming Technique',
        'Drum Set',
        'David Wilson',
        'Continue the Stone "killer" series with a focus on foot control and endurance.',
        '{"1. Practice double strokes with each foot.", "2. Gradually increase tempo.", "3. Maintain consistent foot heights."}',
        '{"1. Use a metronome for accurate timing.", "2. Focus on relaxed ankles and feet.", "3. Challenge yourself with longer practice sessions."}',
        20,
        70,
        120,
        'https://www.example.com/video67'
    ),
    (
        'Double Stroke Roll',
        1,
        1,
        TRUE,
        FALSE,
        'Drumming Technique',
        'Practice Pad',
        'Laura Davis',
        'Practice the double stroke roll for improved hand speed and control.',
        '{"1. Master the double stroke roll technique.", "2. Practice alternating hands.", "3. Work on smooth and even rolls."}',
        '{"1. Use a metronome for precise timing.", "2. Experiment with different dynamics.", "3. Maintain a relaxed grip."}',
        15,
        70,
        120,
        'https://www.example.com/video68'
    ),
    (
        'Single Stroke Roll',
        1,
        1,
        TRUE,
        TRUE,
        'Drumming Technique',
        'Practice Pad',
        'Michael Johnson',
        'Work on your single stroke roll for speed and endurance.',
        '{"1. Master the single stroke roll technique.", "2. Practice both right and left hand rolls.", "3. Focus on consistent and controlled strokes."}',
        '{"1. Use a metronome for accurate timing.", "2. Experiment with different stick heights.", "3. Challenge yourself with extended practice sessions."}',
        20,
        70,
        120,
        'https://www.example.com/video69'
    ),
    (
        'Moving Paradiddle Accents',
        1,
        1,
        TRUE,
        FALSE,
        'Drumming Technique',
        'Drum Set',
        'Sophia Anderson',
        'Enhance your drumming with moving paradiddle accents.',
        '{"1. Practice paradiddle variations.", "2. Add accents on different strokes.", "3. Develop hand control and precision."}',
        '{"1. Use a metronome for timing.", "2. Experiment with dynamic contrast.", "3. Maintain a relaxed grip and wrist motion."}',
        15,
        80,
        140,
        'https://www.example.com/video70'
    ),
    (
        'Flam Accent to Flam Tap',
        1,
        1,
        TRUE,
        TRUE,
        'Drumming Technique',
        'Drum Set',
        'John Smith',
        'Explore the transition from flam accents to flam taps.',
        '{"1. Practice flam accents.", "2. Work on flam tap patterns.", "3. Focus on smooth transitions."}',
        '{"1. Use a metronome for precise timing.", "2. Experiment with flam tap dynamics.", "3. Record your practice for self-evaluation."}',
        20,
        70,
        130,
        'https://www.example.com/video71'
    ),
    (
        'Flam Paradiddle',
        1,
        1,
        TRUE,
        TRUE,
        'Drumming Technique',
        'Drum Set',
        'Emily Davis',
        'Master the flam paradiddle for intricate drumming patterns.',
        '{"1. Practice flam paradiddle rudiment.", "2. Work on speed and control.", "3. Incorporate it into grooves."}',
        '{"1. Use a metronome for timing accuracy.", "2. Experiment with various flam placements.", "3. Maintain a relaxed grip."}',
        15,
        70,
        120,
        'https://www.example.com/video72'
    ),
    (
        'Flam Paradiddle-diddle',
        1,
        1,
        TRUE,
        TRUE,
        'Drumming Technique',
        'Drum Set',
        'Michael Johnson',
        'Enhance your drumming vocabulary with the flam paradiddle-diddle.',
        '{"1. Practice flam paradiddle-diddle rudiment.", "2. Work on speed and precision.", "3. Create dynamic drum fills."}',
        '{"1. Use a metronome for precise timing.", "2. Experiment with accent variations.", "3. Challenge yourself with different tempos."}',
        20,
        70,
        120,
        'https://www.example.com/video73'
    ),
    (
        'Drag Paradiddle',
        1,
        1,
        TRUE,
        FALSE,
        'Drumming Technique',
        'Drum Set',
        'Natalie Carter',
        'Develop your drumming technique with the drag paradiddle.',
        '{"1. Practice the drag paradiddle rudiment.", "2. Focus on hand control.", "3. Incorporate it into drum grooves."}',
        '{"1. Use a metronome for timing accuracy.", "2. Experiment with drag stroke dynamics.", "3. Maintain a relaxed hand technique."}',
        15,
        60,
        110,
        'https://www.example.com/video74'
    ),
    (
        'Ratamacue',
        1,
        1,
        TRUE,
        TRUE,
        'Drumming Technique',
        'Drum Set',
        'Olivia Parker',
        'Master the ratamacue rudiment for complex drum fills.',
        '{"1. Practice ratamacue variations.", "2. Work on speed and accuracy.", "3. Apply it to drumming patterns."}',
        '{"1. Use a metronome for precise timing.", "2. Experiment with different accent placements.", "3. Record your practice sessions."}',
        20,
        60,
        110,
        'https://www.example.com/video75'
    ),
    (
        'Buzz Rolls',
        1,
        1,
        TRUE,
        FALSE,
        'Drumming Technique',
        'Snare Drum',
        'David Wilson',
        'Improve your buzz roll technique for expressive snare drumming.',
        '{"1. Practice buzz rolls with control.", "2. Work on evenness and consistency.", "3. Develop long sustained rolls."}',
        '{"1. Use a metronome for timing accuracy.", "2. Experiment with buzz roll dynamics.", "3. Maintain a relaxed grip and finger control."}',
        15,
        60,
        100,
        'https://www.example.com/video76'
    ),
    (
        'Eighth Note to Triplets',
        1,
        1,
        TRUE,
        TRUE,
        'Drumming Technique',
        'Drum Set',
        'Sophia Anderson',
        'Transition between eighth notes and triplets seamlessly.',
        '{"1. Practice eighth note grooves.", "2. Work on triplet subdivisions.", "3. Develop smooth transitions."}',
        '{"1. Use a metronome for precise timing.", "2. Experiment with dynamics.", "3. Record your transitions for self-assessment."}',
        20,
        70,
        130,
        'https://www.example.com/video77'
    ),
    (
        'Septuplet Accents',
        1,
        1,
        TRUE,
        TRUE,
        'Drumming Technique',
        'Drum Set',
        'John Smith',
        'Add excitement to your drumming with septuplet accents.',
        '{"1. Practice septuplet patterns.", "2. Focus on precise accents.", "3. Incorporate them into drum fills."}',
        '{"1. Use a metronome for timing accuracy.", "2. Experiment with accent placements.", "3. Challenge yourself with various tempos."}',
        15,
        80,
        140,
        'https://www.example.com/video78'
    ),
    (
        'Quintuplet Accents',
        1,
        1,
        TRUE,
        FALSE,
        'Drumming Technique',
        'Drum Set',
        'Emily Davis',
        'Explore quintuplet accents for rhythmic diversity in your drumming.',
        '{"1. Practice quintuplet patterns.", "2. Work on accent dynamics.", "3. Apply them creatively."}',
        '{"1. Use a metronome for precise timing.", "2. Experiment with different accent placements.", "3. Maintain relaxed hand technique."}',
        20,
        60,
        120,
        'https://www.example.com/video79'
    ),
    (
        'Nonuplet Accents',
        1,
        1,
        TRUE,
        TRUE,
        'Drumming Technique',
        'Drum Set',
        'Michael Johnson',
        'Challenge your drumming skills with nonuplet accents.',
        '{"1. Practice nonuplet patterns.", "2. Focus on precise accents.", "3. Integrate them into complex grooves."}',
        '{"1. Use a metronome for precise timing.", "2. Experiment with different accent placements.", "3. Record your drumming to track progress."}',
        15,
        70,
        130,
        'https://www.example.com/video80'
    ),
    (
        'Displaced 16th Note - Hands',
        1,
        1,
        TRUE,
        FALSE,
        'Drumming Technique',
        'Practice Pad',
        'Laura Davis',
        'Work on displaced 16th notes to enhance hand dexterity.',
        '{"1. Practice displaced 16th note patterns.", "2. Focus on hand coordination.", "3. Gradually increase tempo."}',
        '{"1. Use a metronome for timing accuracy.", "2. Experiment with dynamic variations.", "3. Maintain relaxed wrist motion."}',
        20,
        70,
        130,
        'https://www.example.com/video81'
    ),
    (
        'Displaced Triplet - Hands',
        1,
        1,
        TRUE,
        TRUE,
        'Drumming Technique',
        'Practice Pad',
        'Carlos Hernandez',
        'Explore displaced triplets for intricate handwork on the pad.',
        '{"1. Practice displaced triplet patterns.", "2. Work on hand control.", "3. Apply them to drumming exercises."}',
        '{"1. Use a metronome for precise timing.", "2. Experiment with different sticking patterns.", "3. Record your practice sessions."}',
        15,
        80,
        140,
        'https://www.example.com/video82'
    ),
    (
        'Comping Over the Bar Line',
        4,
        4,
        TRUE,
        TRUE,
        'Jazz',
        'Drum Set',
        'Isabella Rodriguez',
        'Improve your jazz drumming by comping over the bar line.',
        '{"1. Practice comping patterns in odd time signatures.", "2. Focus on groove and feel.", "3. Collaborate with other musicians."}',
        '{"1. Use a metronome for timing accuracy.", "2. Experiment with comping variations.", "3. Maintain a relaxed drumming posture."}',
        20,
        80,
        140,
        'https://www.example.com/video83'
    ),
    (
        'Expand on Single Idea',
        4,
        4,
        TRUE,
        TRUE,
        'Jazz',
        'Drum Set',
        'Natalie Carter',
        'Expand on a single musical idea to develop your creativity.',
        '{"1. Choose a simple motif or rhythm.", "2. Experiment with variations and embellishments.", "3. Create a compelling drum solo."}',
        '{"1. Use your ears to guide your improvisation.", "2. Experiment with different textures and dynamics.", "3. Record your improvisations for analysis."}',
        15,
        70,
        130,
        'https://www.example.com/video84'
    ),
    (
        'Cymbal Deep Listening',
        4,
        4,
        TRUE,
        FALSE,
        'Drumming Technique',
        'Drum Set',
        'David Wilson',
        'Enhance your drumming by deep listening to cymbal sounds.',
        '{"1. Focus on the nuances of cymbal tones.", "2. Experiment with different cymbal techniques.", "3. Create expressive cymbal textures."}',
        '{"1. Use your ears to shape your cymbal playing.", "2. Experiment with mallets and brushes.", "3. Collaborate with other percussionists for sonic exploration."}',
        15,
        70,
        120,
        'https://www.example.com/video85'
    ),
    (
        'Hum While Exploring',
        4,
        4,
        TRUE,
        FALSE,
        'Drumming Technique',
        'Drum Set',
        'Olivia Parker',
        'Add a vocal element to your drumming exploration.',
        '{"1. Hum or sing melodies while drumming.", "2. Experiment with vocal rhythms.", "3. Create unique drum and vocal compositions."}',
        '{"1. Use your voice to express musical ideas.", "2. Experiment with vocal harmonies.", "3. Record your drum and vocal sessions for composition purposes."}',
        20,
        60,
        110,
        'https://www.example.com/video86'
    ),
    (
        'Slide Guitar Techniques',
        4,
        4,
        FALSE,
        FALSE,
        'Blues',
        'Slide Guitar',
        'Laura Davis',
        'Enhance your blues slide guitar techniques with expert guidance.',
        '{"1. Learn essential slide guitar fundamentals.", "2. Practice slide vibrato and bending techniques.", "3. Explore various slide positions."}',
        '{"1. Use a glass or metal slide for tone variety.", "2. Experiment with fingerpicking and slide combination.", "3. Record your sessions for tracking progress."}',
        15,
        60,
        100,
        'https://www.example.com/video87'
    ),
    (
        'Advanced Jazz Saxophone',
        4,
        4,
        FALSE,
        FALSE,
        'Jazz',
        'Saxophone',
        'Michael Johnson',
        'Advance your jazz saxophone skills with complex improvisations.',
        '{"1. Explore advanced jazz scales and modes.", "2. Practice intricate saxophone phrasing.", "3. Focus on dynamic expression."}',
        '{"1. Maintain precise timekeeping in complex rhythms.", "2. Experiment with solo saxophone performances.", "3. Collaborate with other musicians for live jazz sessions."}',
        20,
        80,
        140,
        'https://www.example.com/video88'
    ),
    (
        'Latin Jazz Piano Improvisation',
        4,
        4,
        FALSE,
        FALSE,
        'Latin',
        'Piano',
        'Carlos Martinez',
        'Improve your Latin jazz piano skills with improvisational techniques.',
        '{"1. Explore Latin jazz chord progressions.", "2. Practice improvisation over Latin rhythms.", "3. Focus on creating melodic phrases."}',
        '{"1. Maintain precise timekeeping in Latin grooves.", "2. Experiment with chord voicings and extensions.", "3. Collaborate with a percussionist for Latin jazz fusion."}',
        20,
        70,
        130,
        'https://www.example.com/video89'
    ),
    (
        'Advanced Ballet Techniques',
        4,
        4,
        FALSE,
        FALSE,
        'Ballet',
        'Dance',
        'Sophia Anderson',
        'Advance your ballet skills with challenging techniques and choreography.',
        '{"1. Learn intricate ballet combinations and variations.", "2. Practice balance and turns.", "3. Focus on conveying emotion through dance."}',
        '{"1. Maintain proper ballet posture and alignment.", "2. Experiment with graceful arm movements.", "3. Collaborate with a live orchestra for classical ballet performances."}',
        15,
        60,
        110,
        'https://www.example.com/video90'
    ),
    (
        'Advanced Acoustic Guitar Fingerpicking',
        4,
        4,
        FALSE,
        FALSE,
        'Acoustic',
        'Guitar',
        'Olivia Parker',
        'Expand your acoustic guitar fingerpicking skills with complex patterns.',
        '{"1. Learn fingerstyle arrangements of classic songs.", "2. Practice fingerpicking with multiple fingers.", "3. Explore thumb and finger independence."}',
        '{"1. Maintain a steady rhythm in fingerstyle playing.", "2. Experiment with dynamic variations.", "3. Collaborate with a vocalist for acoustic duets."}',
        20,
        60,
        110,
        'https://www.example.com/video91'
    ),
    (
        'Flute Solo Mastery',
        4,
        4,
        FALSE,
        FALSE,
        'Classical',
        'Flute',
        'Natalie Carter',
        'Master the art of solo flute performance with advanced techniques.',
        '{"1. Learn complex classical flute compositions.", "2. Practice intricate phrasing and ornamentation.", "3. Focus on expressive dynamics."}',
        '{"1. Maintain precise breath control for long phrases.", "2. Experiment with flute vibrato techniques.", "3. Record your solo performances for evaluation."}',
        5,
        70,
        120,
        'https://www.example.com/video92'
    ),
    (
        'Funk Bass Grooves',
        4,
        4,
        FALSE,
        FALSE,
        'Funk',
        'Bass Guitar',
        'Carlos Hernandez',
        'Groove like a funk master with advanced bass guitar techniques.',
        '{"1. Explore funky bass lines and syncopations.", "2. Practice slap and pop techniques.", "3. Focus on pocket and groove."}',
        '{"1. Maintain a tight rhythm with the drummer.", "2. Experiment with bass fills and solos.", "3. Collaborate with a funk band for live performances."}',
        10,
        60,
        100,
        'https://www.example.com/video93'
    ),
    (
        'Advanced Flamenco Guitar',
        4,
        4,
        FALSE,
        FALSE,
        'Flamenco',
        'Guitar',
        'Isabella Martinez',
        'Advance your flamenco guitar skills with complex rhythmic patterns.',
        '{"1. Learn traditional flamenco guitar forms.", "2. Practice intricate picado and rasgueado techniques.", "3. Focus on emotional expression in your playing."}',
        '{"1. Maintain precise timing in intricate rhythms.", "2. Experiment with fast and precise strumming.", "3. Collaborate with a flamenco dancer for live performances."}',
        25,
        70,
        130,
        'https://www.example.com/video94'
    ),
    (
        'Advanced Jazz Drumming',
        4,
        4,
        FALSE,
        FALSE,
        'Jazz',
        'Drum Set',
        'Emily Davis',
        'Enhance your jazz drumming with complex rhythms and improvisation.',
        '{"1. Explore advanced jazz drumming patterns.", "2. Practice intricate cymbal work.", "3. Focus on creating dynamic drum solos."}',
        '{"1. Maintain precise timekeeping in complex jazz arrangements.", "2. Experiment with drum solo improvisation.", "3. Record your jazz performances for self-assessment."}',
        30,
        80,
        140,
        'https://www.example.com/video95'
    ),
    (
        'Advanced Yoga Flow',
        4,
        4,
        FALSE,
        FALSE,
        'Yoga',
        'Yoga Mat',
        'Sophia Anderson',
        'Challenge yourself with an advanced yoga flow sequence.',
        '{"1. Practice challenging yoga poses.", "2. Focus on deep stretches and balance.", "3. Enhance your mindfulness and breath control."}',
        '{"1. Maintain proper alignment and body awareness.", "2. Experiment with advanced variations of poses.", "3. Keep a yoga journal to track your progress."}',
        35,
        70,
        120,
        'https://www.example.com/video96'
    ),
    (
        'Advanced Flamenco Dance',
        4,
        4,
        FALSE,
        FALSE,
        'Flamenco',
        'Dance',
        'Michael Johnson',
        'Master the intricate footwork and passion of flamenco dance.',
        '{"1. Learn advanced flamenco dance forms.", "2. Practice intricate footwork and palmas.", "3. Focus on expressing intense emotions through dance."}',
        '{"1. Maintain precise timing in complex dance rhythms.", "2. Experiment with improvisational footwork.", "3. Collaborate with live flamenco musicians for authentic performances."}',
        40,
        70,
        130,
        'https://www.example.com/video97'
    ),
    (
        'Advanced Tai Chi Forms',
        4,
        4,
        FALSE,
        FALSE,
        'Tai Chi',
        'Tai Chi Mat',
        'Olivia Parker',
        'Improve your Tai Chi skills with advanced forms and energy flow.',
        '{"1. Learn complex Tai Chi forms and transitions.", "2. Practice Qi Gong for energy cultivation.", "3. Focus on the harmony of movement and breath."}',
        '{"1. Maintain precise balance and posture.", "2. Experiment with slow and flowing movements.", "3. Meditate to enhance mindfulness in your practice."}',
        45,
        60,
        110,
        'https://www.example.com/video98'
    ),
    (
        'Advanced Ballet Choreography',
        4,
        4,
        FALSE,
        FALSE,
        'Ballet',
        'Dance',
        'David Wilson',
        'Choreograph intricate ballet routines and showcase your artistry.',
        '{"1. Create complex ballet choreography.", "2. Practice graceful leaps and pirouettes.", "3. Focus on storytelling through dance."}',
        '{"1. Maintain precise footwork and alignment.", "2. Experiment with emotional expression in dance.", "3. Collaborate with a ballet company for live performances."}',
        50,
        80,
        140,
        'https://www.example.com/video99'
    ),
    (
        'Advanced Acoustic Guitar Fingerstyle',
        4,
        4,
        FALSE,
        FALSE,
        'Acoustic',
        'Guitar',
        'Laura Davis',
        'Master intricate fingerstyle guitar arrangements with finesse.',
        '{"1. Learn advanced fingerstyle guitar compositions.", "2. Practice fingerpicking intricacies.", "3. Focus on conveying emotions through your playing."}',
        '{"1. Maintain precise fingerpicking patterns.", "2. Experiment with alternate tunings.", "3. Record your fingerstyle guitar performances for analysis."}',
        55,
        60,
        110,
        'https://www.example.com/video100'
    );