export const ERRORS_ACTIONS = {
  CLEAR_LOGIN_ERROR: 'CLEAR_LOGIN_ERROR',
  LOGIN_INPUT_ERROR: 'LOGIN_INPUT_ERROR',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_FAILED_NO_CODE: 'LOGIN_FAILED_NO_CODE',
  CLEAR_REGISTRATION_ERROR: 'CLEAR_REGISTRATION_ERROR',
  REGISTRATION_INPUT_ERROR: 'REGISTRATION_INPUT_ERROR',
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
};
