export const SESSION_HISTORY_ACTIONS = {
  SET_SESSIONS_THIS_WEEK: 'SET_SESSIONS_THIS_WEEK',
  SET_SESSIONS_THIS_MONTH: 'SET_SESSIONS_THIS_MONTH',
  SET_SESSIONS_THIS_YEAR: 'SET_SESSIONS_THIS_YEAR',
  SET_ALL_SESSIONS: 'SET_ALL_SESSIONS',
};
