export const SESSION_ACTIONS = {
  SET_SESSION: 'SET_SESSION',
  SET_EXERCISES: 'SET_EXERCISES',
  SET_IS_COMPLETE: 'SET_IS_COMPLETE',
  RESET_SESSION: 'RESET_SESSION',
  SET_CURRENT_EXERCISE: 'SET_CURRENT_EXERCISE',
  ADD_EXERCISE_TO_COMPLETED: 'ADD_EXERCISE_TO_COMPLETED',
  RESET_COMPLETED_EXERCISES: 'RESET_COMPLETED_EXERCISES',
};
