export const SESSION_FORM_ACTIONS = {
  SET_TYPES: 'SET_TYPES',
  SET_SELECTED_TYPE: 'SET_SELECTED_TYPE',
  REMOVE_SELECTED_TYPE: 'REMOVE_SELECTED_TYPE',
  SET_SELECTED_TYPE_FOCUS: 'SET_SELECTED_TYPE_FOCUS',
  SET_TIME_IN_MINUTES: 'SET_TIME_IN_MINUTES',
};
