export const SESSION_HISTORY_SAGA_ACTIONS = {
  GET_SESSIONS_THIS_WEEK: 'GET_SESSIONS_THIS_WEEK',
  GET_SESSIONS_THIS_MONTH: 'GET_SESSIONS_THIS_MONTH',
  GET_SESSIONS_THIS_YEAR: 'GET_SESSIONS_THIS_YEAR',
  GET_ALL_SESSIONS: 'GET_ALL_SESSIONS',
};
