export const SESSION_FORM_ACTIONS = {
  SET_FOCUS: 'SET_FOCUS',
  SET_SPEED_AND_AGILITY_TYPES: 'SET_SPEED_AND_AGILITY_TYPES',
  SET_CREATIVITY_AND_IMPROVISATION_TYPES:
    'SET_CREATIVITY_AND_IMPROVISATION_TYPES',
  SET_STYLE_AND_VOCABULARY_TYPES: 'SET_STYLE_AND_VOCABULARY_TYPES',
  SET_PRECISION_AND_TIMEKEEPING_TYPES: 'SET_PRECISION_AND_TIMEKEEPING_TYPES',
  SET_TIME_IN_MINUTES: 'SET_TIME_IN_MINUTES',
};
