INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Full Strokes', 1, 1, TRUE, FALSE, 'N/A', 'Practice Pad', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"1. 1 full stroke with right hand (RH), followed by 1 full stroke with left hand (LH). Repeat 16x, creating constant eighth notes.", "2. 2 full strokes RH, 2 full strokes LH. Repeat 8x", "3. 3 full strokes RH, 3 full strokes LH. Repeat 8x", "4. 4 full strokes RH, 4 full strokes LH. Repeat 8x", "5. 5 full strokes RH, 5 full strokes LH. Repeat 8x", "6. 6 full strokes RH, 6 full strokes LH. Repeat 8x", "7. Increase tempo by 5 bmp and repeat"}', '{"1. Go slow!", "2. Strive for an even sound between both hands. ", "3. If the stick falls out of your hand, that''s okay. It means you are not gripping the stick too hard."}', 5, 80, 100, 'https://youtu.be/UBVkgoSpqv0');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Down Strokes', 1, 1, TRUE, FALSE, 'N/A', 'Practice Pad', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"1. 4 full strokes (eighth notes) followed by 1 downstroke (quarter note) x8", "2. 2 full strokes followed by 1 downstroke", "3. 1 full stroke followed by 1 downstroke"}', '{"Aim to keep the sound of your down strokes as close as possible to the sound of your full strokes. Stay relaxed."}', 5, 80, 120, 'https://youtu.be/a70KmT1kXgE');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Taps & Up Strokes', 1, 1, TRUE, FALSE, 'N/A', 'Practice Pad', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 80, 120, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Stone "killer" pt 1 - Hands', 1, 1, TRUE, FALSE, 'N/A', 'Practice Pad', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 80, 120, 'https://youtu.be/ktqVdCru-VM');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Stone "killer" pt 2 - Hands', 1, 1, TRUE, FALSE, 'N/A', 'Practice Pad', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 80, 120, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Foot Triplets', 1, 2, TRUE, FALSE, 'N/A', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 60, 100, 'https://youtu.be/OSOC2ODNg-U?si=oYFDU4eIXun5mSyW&t=174');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Stone "killer" pt 1 - Feet', 1, 2, TRUE, FALSE, 'N/A', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 50, 80, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Stone "killer" pt 2 - Feet', 1, 2, TRUE, FALSE, 'N/A', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 50, 80, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Double Stroke Roll', 1, 3, TRUE, FALSE, 'N/A', 'Snare Drum', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 60, 100, 'https://youtu.be/UL8WSdyAGgs');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Single Stroke Roll', 1, 3, TRUE, FALSE, 'N/A', 'Snare Drum', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 60, 100, 'https://youtu.be/98zaTHDdB9s');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Moving Paradiddle Accents', 1, 3, FALSE, FALSE, 'N/A', 'Snare Drum', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 60, 120, 'https://youtu.be/r7c2Pn-iUY4');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Flam Accent to Flam Tap', 1, 3, FALSE, FALSE, 'N/A', 'Snare Drum', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 60, 120, 'https://youtu.be/fuL3igtVDqg?si=1KKv4sqhKMRzDJek&t=37');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Flam Paradiddle', 1, 3, FALSE, FALSE, 'N/A', 'Snare Drum', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 60, 120, 'https://www.youtube.com/watch?v=mFJvKONt1_Y');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Flam Paradiddle-diddle', 1, 3, FALSE, FALSE, 'N/A', 'Snare Drum', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 60, 120, 'https://www.youtube.com/watch?v=ek3AKKMSLAY');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Drag Paradiddle', 1, 3, FALSE, FALSE, 'N/A', 'Snare Drum', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 60, 120, 'https://www.youtube.com/watch?v=KIkL8d4VVIc');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Ratamacue', 1, 3, FALSE, FALSE, 'N/A', 'Snare Drum', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 60, 120, 'https://www.youtube.com/watch?v=EqAKWvijlgA');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Buzz Rolls', 1, 3, TRUE, FALSE, 'N/A', 'Snare Drum', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 60, 120, 'https://youtu.be/dksnMtV5Suc?si=TqgfqqcGs3dCKzov&t=76');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Eighth Note to Triplets', 4, 11, TRUE, FALSE, 'N/A', 'Practice Pad', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Use the resource sheet provided to transition from eighth notes to triplets on a single surface, utilizing a single dynamic. If you have time, try doing this same exercise at a new dynamic and/or change up the surfaces you are playing on. "}', '{"Although this exercise seems simple, focus on what each rate feels like in your body. "}', 5, 70, 160, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Septuplet Accents', 4, 11, FALSE, FALSE, 'N/A', 'Practice Pad', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 40, 90, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Quintuplet Accents', 4, 11, FALSE, FALSE, 'N/A', 'Practice Pad', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 60, 100, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Nonuplet Accents', 4, 11, FALSE, FALSE, 'N/A', 'Practice Pad', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 40, 80, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('7/8 Grooving', 4, 12, FALSE, FALSE, 'N/A', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 8, 60, 120, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('9/8 Grooving', 4, 12, FALSE, FALSE, 'N/A', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 8, 60, 120, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('11/8 Grooving', 4, 12, FALSE, FALSE, 'N/A', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 8, 60, 120, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Displaced 16th Note - Hands', 4, 10, FALSE, FALSE, 'N/A', 'Practice Pad', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 60, 100, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Displaced 16th Note - Groove', 4, 10, FALSE, FALSE, 'Rock, Funk', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 60, 100, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Displaced Triplet - Hands', 4, 10, FALSE, FALSE, 'N/A', 'Practice Pad', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 60, 100, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Displaced Triplet - Groove', 4, 10, FALSE, FALSE, 'Rock, Funk', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 60, 100, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Slow Burn', 4, 10, FALSE, FALSE, 'Rock ', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 8, 20, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('16th to Quintuplet Groove', 4, 10, FALSE, FALSE, 'Rock, Jazz', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 50, 90, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('David Garibaldi - What is Hip ', 3, 7, FALSE, FALSE, 'Funk', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 60, 200, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Elvin Jones - Lonnie''s Lament', 3, 7, FALSE, FALSE, 'Jazz', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 60, 200, 'https://youtu.be/e8x-2-Zq3FQ?si=zxtN6FdJ9OScZdmb&t=192');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Elvin Jones - Summertime', 3, 7, FALSE, FALSE, 'Jazz', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 60, 200, 'https://youtu.be/tC1PzuBiduA?si=EBdnlyBMr1iEIu2Y');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Tony Williams - Hat and Beard', 3, 7, FALSE, FALSE, 'Jazz', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 60, 200, 'https://www.youtube.com/watch?v=7tnPkQufnZY');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Tony Allen - Water No Get Enemy', 3, 7, FALSE, FALSE, 'Afrobeat', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 60, 200, 'https://www.youtube.com/watch?v=IQBC5URoF0s');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Comping Over the Bar Line', 3, 8, FALSE, FALSE, 'Jazz', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 70, 110, 'https://www.youtube.com/watch?v=BVwPOUgbfRA');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Linear Kick Fills', 3, 8, FALSE, FALSE, 'Rock, Gospel, Jazz', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 50, 100, 'https://youtu.be/IvGhAnUbBv4?si=KZsqrpG1DE4m8cB2&t=179');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Swung to Straight', 3, 9, FALSE, FALSE, 'Funk', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 60, 120, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Bossa Nova Variations', 3, 9, FALSE, FALSE, 'Bossa Nova', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 90, 140, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('LH Comping - Jazz', 3, 9, FALSE, FALSE, 'Jazz', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 90, 220, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('LH & RF Comping - Jazz', 3, 9, FALSE, FALSE, 'Jazz', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and only allow the stick to rebound at a height that is lower than the starting position. This stroke goes from high to low.
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 90, 220, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Storytelling Arc', 2, 4, FALSE, FALSE, 'N/A', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 60, 200, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Expand on Single Idea', 2, 4, FALSE, FALSE, 'N/A', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 60, 200, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Use of Silence', 2, 4, FALSE, TRUE, 'N/A', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 60, 200, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Cymbal Deep Listening', 2, 6, FALSE, TRUE, 'N/A', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 60, 200, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Hum While Exploring', 2, 6, FALSE, TRUE, 'N/A', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 5, 60, 200, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Trading 4''s', 2, 5, FALSE, FALSE, 'Jazz', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 80, 220, '');
INSERT INTO EXERCISES (NAME, TYPE_ID, FOCUS_ID, WARMUP, COOLDOWN, GENRE, INSTRUMENT, TEACHER, DESCRIPTION, DIRECTIONS, REMEMBER, MINIMUM_TIME_MINUTES, BPM_MIN, BPM_MAX, VIDEO_LINK) VALUES ('Changing Dynamics', 2, 5, FALSE, FALSE, 'N/A', 'Drum Set', 'N/A', '
  The objective is to throw the stick with effort and allow the stick to rebound back to its original position. 
  Make sure your wrist is returning to its original position before the stick does, otherwise it will get in the way of the stick''s natural rebound. 
  ', '{"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}', '{"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt."}', 10, 80, 220, '');
